### ISSUE TITLE
ESLint errors on Windows

### ISSUE THREAD

**Issue by OKinane** [midrissi/func-loc#6]
ESLint report CRLF end of line as errors.

In Windows, if git option core.autocrlf is set to true, all files will have CRLF eol after clone.

To fix this, you can clone with this command line:
`git clone -c core.autocrlf=false https://github.com/midrissi/func-loc.git`

**Comment by midrissi** [comment]
I will add that to `.gitattributes` file, and come back to you once it has been fixed. Thanks a lot 👍

**Comment by midrissi** [comment]
Done! And added a travis os config for that
