### ISSUE TITLE
Unit tests fail in Windows

### ISSUE THREAD

**Issue by OKinane** [midrissi/func-loc#7]
On Windows, `npm test` fails with errors like:

![image](https://user-images.githubusercontent.com/15254824/69008553-ece74c80-094b-11ea-8702-155ac971b7b4.png)

What the paths returned by `locate(fn)` should look like in Windows ?

Windows 10 v1903
Node 10.16.3

**Comment by midrissi** [comment]
Thank you for the report. I will check it out this evening. To be honest, I did not run the tests on Windows. I will do and come back to you.

**Comment by midrissi** [comment]
I have pushed the fix f7d5fb794b5fa2a62583ce74f8901fca79251f8a

Can you try if it is working for you?

Thank you 👍

**Comment by OKinane** [comment]
All green now, thanks !
